import React from "react";
import jsPDF from "jspdf";

const RoadmapCompletedCard = ({ onRegenerate, userName = "AI Learner" }) => {
  const downloadCertificate = () => {
    const doc = new jsPDF("landscape");

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    // ================= OUTER BORDER =================
    doc.setDrawColor(0, 120, 180);
    doc.setLineWidth(2);
    doc.rect(8, 8, pageWidth - 16, pageHeight - 16);

    // ================= INNER BORDER =================
    doc.setDrawColor(180, 220, 255);
    doc.setLineWidth(0.6);
    doc.rect(12, 12, pageWidth - 24, pageHeight - 24);

    // ================= PLATFORM TITLE =================
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(70, 70, 70);
    doc.text(
      "AI CAREER COACH PLATFORM",
      pageWidth / 2,
      25,
      { align: "center" }
    );

    // ================= MAIN TITLE =================
    doc.setFont("times", "bold");
    doc.setFontSize(30);
    doc.setTextColor(0, 102, 153);
    doc.text(
      "CERTIFICATE OF COMPLETION",
      pageWidth / 2,
      45,
      { align: "center" }
    );

    // Decorative line
    doc.line(70, 52, pageWidth - 70, 52);

    // ================= INTRO TEXT =================
    doc.setFont("helvetica", "normal");
    doc.setFontSize(13);
    doc.setTextColor(60, 60, 60);

    doc.text(
      "This certificate is proudly presented to",
      pageWidth / 2,
      72,
      { align: "center" }
    );

    // ================= USER NAME =================
    doc.setFont("times", "bold");
    doc.setFontSize(24);
    doc.setTextColor(20, 20, 20);

    doc.text(
      userName,
      pageWidth / 2,
      88,
      { align: "center" }
    );

    doc.line(90, 92, pageWidth - 90, 92);

    // ================= DESCRIPTION =================
    doc.setFont("helvetica", "normal");
    doc.setFontSize(13);

    doc.text(
      "For successfully completing the AI-powered Career Development Roadmap",
      pageWidth / 2,
      112,
      { align: "center" }
    );

    doc.text(
      "including resume analysis, skill improvement, interview preparation,",
      pageWidth / 2,
      123,
      { align: "center" }
    );

    doc.text(
      "and structured learning path execution.",
      pageWidth / 2,
      134,
      { align: "center" }
    );

    // ================= CERTIFICATE ID =================
    const certificateId =
      "ACC-" + Math.random().toString(36).substring(2, 8).toUpperCase();

    doc.setFontSize(11);
    doc.setTextColor(80, 80, 80);

    doc.text(
      `Certificate ID: ${certificateId}`,
      25,
      pageHeight - 55
    );

    doc.text(
      `Issue Date: ${new Date().toLocaleDateString()}`,
      25,
      pageHeight - 45
    );

    // ================= SIGNATURES =================
    doc.setDrawColor(0);

    doc.line(
      60,
      pageHeight - 35,
      110,
      pageHeight - 35
    );
    doc.text("Platform Supervisor", 85, pageHeight - 28, {
      align: "center",
    });

    doc.line(
      pageWidth - 110,
      pageHeight - 35,
      pageWidth - 60,
      pageHeight - 35
    );
    doc.text("AI System", pageWidth - 85, pageHeight - 28, {
      align: "center",
    });

    // ================= FOOTER =================
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);

    doc.text(
      "This certificate is automatically generated by the AI Career Coach Platform.",
      pageWidth / 2,
      pageHeight - 12,
      { align: "center" }
    );

    doc.save("AI_Career_Certificate.pdf");
  };

  return (
    <div className="
      mt-12
      rounded-[32px]
      overflow-hidden
      border border-emerald-500/20
      bg-gradient-to-br from-emerald-500/10 via-slate-900/40 to-cyan-500/10
      backdrop-blur-xl
      p-8 md:p-12
      text-center
    ">

      <h2 className="text-3xl md:text-4xl font-black mb-3">
        Learning Journey Completed
      </h2>

      <p className="max-w-2xl mx-auto text-slate-300 text-sm md:text-base">
        The AI Career Roadmap has been successfully completed. Download your official certificate or generate a new roadmap.
      </p>

      <div className="
        flex flex-col sm:flex-row
        justify-center
        gap-4
        mt-10
      ">

        <button
          onClick={downloadCertificate}
          className="
            h-12 px-6
            rounded-2xl
            bg-white/[0.05]
            border border-white/10
            font-semibold
            hover:bg-white/[0.08]
            transition
          "
        >
          Download Certificate
        </button>

        <button
          onClick={onRegenerate}
          className="
            h-12 px-6
            rounded-2xl
            bg-gradient-to-r from-cyan-500 to-blue-500
            font-semibold
            hover:scale-[1.02]
            transition
            shadow-lg shadow-cyan-500/20
          "
        >
          Regenerate Roadmap
        </button>

      </div>
    </div>
  );
};

export default RoadmapCompletedCard;