import React from "react";
import { CheckCircle, AlertCircle, Star } from "lucide-react";
/**
 * ResultsSection Component
 * This component displays the final AI analysis results of the uploaded resume.
 * It presents structured insights generated by the backend + AI system, including:
  
  - Resume summary (AI-generated overview)
  - Detected job role
  - Overall score (0–100) and calculated experience level (Junior / Mid / Senior)
  - Extracted skills with individual scoring
  - Identified skill gaps
  - Actionable career recommendations
 
 * The component also includes safe fallbacks to handle missing or incomplete data,
 * ensuring a stable and user-friendly UI.
 
 * It acts as the final visualization layer in the Resume Analyzer flow,
 * transforming raw AI output into a clear, interactive dashboard for the user.
 */

const ResultsSection = ({ results, onReset }) => {

  // SAFE FALLBACKS 
  const skills = results?.skills || [];

  const gaps = results?.gaps?.length
    ? results.gaps
    : ["No skill gaps detected 🎉"];

  const recommendations = results?.recommendations?.length
    ? results.recommendations
    : ["Keep improving your resume quality and add measurable achievements."];

  const score = results?.overallScore || 0;

  // LEVEL LOGIC
  const getLevel = (score) => {
    if (score >= 85) return "Senior";
    if (score >= 60) return "Mid";
    if (score >= 40) return "Junior";
    return "Rejected/Incomplete Resume";
  };

   return (
    <div className="min-h-screen bg-black/40 backdrop-blur-xl px-4 sm:px-6 lg:px-10 py-10">

      <div className="max-w-6xl mx-auto space-y-8">

        {/* ================= HEADER SUMMARY BAR ================= */}
        <div className="bg-black/30 border border-white/10 rounded-2xl p-6 flex flex-col lg:flex-row lg:items-center lg:justify-between gap-6">

          {/* LEFT */}
          <div>
            <h2 className="text-2xl sm:text-3xl font-black text-white">
              Resume Analysis Result
            </h2>

            <p className="text-gray-400 text-sm mt-1">
              AI-powered breakdown of your resume performance
            </p>

            {results?.role && (
              <p className="text-sm text-gray-400 mt-2">
                Detected Role:{" "}
                <span className="text-blue-400 font-semibold">
                  {results.role}
                </span>
              </p>
            )}
          </div>

          {/* RIGHT METRICS */}
          <div className="flex gap-6">

            <div className="text-center">
              <div className="text-2xl font-bold text-blue-400">
                {score}
                <span className="text-gray-500 text-sm">/100</span>
              </div>
              <div className="text-xs text-gray-400">Score</div>
            </div>

            <div className="text-center">
              <div className="text-2xl font-bold text-indigo-400">
                {skills.length}
              </div>
              <div className="text-xs text-gray-400">Skills</div>
            </div>

            <div className="text-center">
              <div className="text-sm font-bold text-gray-200">
                {getLevel(score)}
              </div>
              <div className="text-xs text-gray-400">Level</div>
            </div>

          </div>
        </div>

        {/* ================= SKILLS SECTION ================= */}
        <div className="bg-black/20 border border-white/10 rounded-2xl p-6">

          <div className="flex items-center gap-3 mb-6">
            <Star className="w-6 h-6 text-yellow-400" />
            <h3 className="text-xl font-bold text-white">
              Extracted Skills
            </h3>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">

            {skills.map((skill, i) => (
              <div
                key={i}
                className="border border-white/10 rounded-xl p-4 bg-white/5"
              >
                <div className="flex justify-between mb-2">
                  <span className="font-medium text-white text-sm">
                    {skill.name}
                  </span>
                  <span className="text-gray-400 text-sm">
                    {skill.score}%
                  </span>
                </div>

                <div className="w-full h-2 bg-gray-800 rounded-full">
                  <div
                    className="h-2 bg-gradient-to-r from-blue-500 to-indigo-600 rounded-full"
                    style={{ width: `${skill.score}%` }}
                  />
                </div>
              </div>
            ))}

          </div>
        </div>

        {/* ================= ANALYSIS GRID ================= */}
        <div className="grid lg:grid-cols-2 gap-6">

          {/* GAPS */}
          <div className="bg-black/20 border border-orange-400/20 rounded-2xl p-6">

            <div className="flex items-center gap-2 mb-5 text-orange-400">
              <AlertCircle className="w-5 h-5" />
              <h3 className="text-lg font-bold">Skill Gaps</h3>
            </div>

            <div className="space-y-3">
              {gaps.map((gap, i) => (
                <div key={i} className="flex gap-3">
                  <span className="text-orange-400 mt-1">•</span>
                  <p className="text-gray-300 text-sm">{gap}</p>
                </div>
              ))}
            </div>
          </div>

          {/* RECOMMENDATIONS */}
          <div className="bg-black/20 border border-emerald-400/20 rounded-2xl p-6">

            <div className="flex items-center gap-2 mb-5 text-emerald-400">
              <CheckCircle className="w-5 h-5" />
              <h3 className="text-lg font-bold">Recommendations</h3>
            </div>

            <div className="space-y-3">
              {recommendations.map((rec, i) => (
                <div key={i} className="flex gap-3">
                  <span className="text-emerald-400 mt-1">•</span>
                  <p className="text-gray-300 text-sm">{rec}</p>
                </div>
              ))}
            </div>

          </div>

        </div>

        {/* ================= ACTION ================= */}
        <div className="flex justify-center pt-6">

          <button
            onClick={onReset}
            className="
              px-8 py-3
              rounded-xl
              bg-gradient-to-r from-blue-600 to-indigo-600
              font-semibold
              hover:scale-105 transition
              shadow-lg shadow-blue-500/20
            "
          >
            Analyze Another Resume
          </button>

        </div>

      </div>
    </div>
  );
};

export default ResultsSection;